"""Changed summarization type from VARCHAR to TEXT

Revision ID: 31e51601ef45
Revises: ba03da2e86f1
Create Date: 2025-06-23 11:15:48.997104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31e51601ef45'
down_revision: Union[str, Sequence[str], None] = 'ba03da2e86f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('embeddings', 'summarization',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('key_insights', 'key_insight',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('key_insights', 'key_insight',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('embeddings', 'summarization',
               existing_type=sa.TEXT(),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=False)
    # ### end Alembic commands ###
