"""Add index to tag

Revision ID: 439b51d25c45
Revises: aaf8f45c98b3
Create Date: 2025-06-19 06:45:17.941838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '439b51d25c45'
down_revision: Union[str, Sequence[str], None] = 'aaf8f45c98b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('tags_tag_key'), 'tags', type_='unique')
    op.create_index(op.f('ix_tags_tag'), 'tags', ['tag'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tags_tag'), table_name='tags')
    op.create_unique_constraint(op.f('tags_tag_key'), 'tags', ['tag'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
